# Azure Kinect SDK 相机配置文件# 坐标变换配置
camera:
  width: 1280
  height: 720
  fps: 30
  mode: "default" # 相机模式，可选值："default", "infrared"
transform:
  # 相机旋转矩阵 R (3x3)
  rotation:
    - [0.2273, 0.3271, 0.9172]
    - [0.0787, -0.9450, 0.3175]
    - [0.9706, 0 , -0.2406 ]
  # 平移向量 T (x, y, z) 单位：米，即相机在机器人坐标系中的位置
  translation: [0.32217, -0.33466, 0.62044]

# 算法阈值
params:
  min_dist: 0.01
  max_dist: 2.0