# Azure Kinect SDK 相机配置文件# 坐标变换配置
camera:
  width: 1280
  height: 720
  fps: 30
  mode: "default" # 相机模式，可选值："default", "infrared"
transform:
  # 相机旋转矩阵 R (3x3)
  rotation:
    - [-0.085757, -0.104509, 0.990819]
    - [0.0, 0.994483, 0.104895]
    - [-0.996316, 0.008995, -0.085284]
  # 平移向量 T (x, y, z) 单位：米，即相机在机器人坐标系中的位置
  translation: [0.32521, -0.31991, 0.62596]

# 算法阈值
params:
  min_dist: 0.01
  max_dist: 2.0